#!/bin/sh

if [ -z "$1" ]
then
    target=check-ref.py
else
    target="$1"
fi

export PYTHONPATH=`dirname $0`

msg_template='--msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}"'
pylint --rcfile=/dev/null --errors-only "$msg_template" --reports=n $target
